version: "3"

networks:
  main:

services:
  audit:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    networks:
      - main
    volumes:
      - ./scripts:/opt/app-root/src/scripts
    env_file:
      - ${APP_ENV}
    command: >
      /bin/bash -c "./run.sh"