name: Deploy
description: Deploy to OpenShift namespace

inputs:
  environment:
    description: the environment to deploy to
    required: true
  username: 
    description: docker registry username
    required: true
  password:
    description: docker registry password
    required: true
  openshift_server_url: 
    description: openshift server url
    required: true
  openshift_token:
    description: openshift server token
    required: true
  image_digest:
    description: openshift image digest
    required: true
  namespace:
    description: namespace where we want to deploy the image
    required: true
  job_status:
    description: Notifies status of job in Rocket Chat
    required: true
  rocketchat_webhook:
    description: defining the rocket chat webhook url
    required: true
  github_token:
    description: secret token used to webhook github and rocketchat 
    required: true 

runs:
    using: composite
    steps:
      - name: Log in to the GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ inputs.username }}
          password: ${{ inputs.password }}

      - name: Setup Openshift CLI
        uses: redhat-actions/oc-login@v1
        with:
          environment: ${{ inputs.environment }}
          openshift_server_url: ${{ inputs.openshift_server_url }}
          openshift_token: ${{ inputs.openshift_token }}

      - name: login in to OpenShift container registry
        shell: bash
        run: |
          oc registry login

      - name: Tag the image in the GHCR as dev
        shell: bash
        run: |
          docker pull ghcr.io/bcgov/von-bc-registries-audit/audit:${{ inputs.image_digest }}
          docker tag ghcr.io/bcgov/von-bc-registries-audit/audit:${{ inputs.image_digest }} ghcr.io/bcgov/von-bc-registries-audit/audit:dev
          docker push ghcr.io/bcgov/von-bc-registries-audit/audit:dev

      - name: Tag the image in the OpenShift container registry as dev
        shell: bash
        run: |
          docker pull ghcr.io/bcgov/von-bc-registries-audit/audit:${{ inputs.image_digest }}
          docker tag ghcr.io/bcgov/von-bc-registries-audit/audit:${{ inputs.image_digest }} image-registry.apps.silver.devops.gov.bc.ca/ca7f8f-tools/audit:dev
          docker push image-registry.apps.silver.devops.gov.bc.ca/ca7f8f-tools/audit:dev

      - name: Trigger Openshift
        shell: bash
        run: |
          echo starting rollout in ${{ inputs.namespace }}
          oc -n ${{ inputs.namespace }} rollout status dc/audit --watch

      - name: Rocket.Chat Notification
        uses: RocketChat/Rocket.Chat.GitHub.Action.Notification@master
        if: always()
        with:
          type: ${{ inputs.job_status }}
          job_name: '*Deployment to Dev*'
          mention: 'here'
          mention_if: 'failure'
          channel: '#test-gha'
          url: ${{ inputs.rocketchat_webhook }}
          commit: true
          token: ${{ inputs.github_token }}