name: Pull Request
on:
  workflow_dispatch:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  builds:
    permissions:
      packages: write
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Builds
        uses: bcgov-nr/action-conditional-container-builder@v1.1.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          package: audit
          build_context: .
          build_file: docker/Dockerfile
          tag: latest

      - name: Docker login
        uses: docker/login-action@v2
        with:
          registry: ghcr.io 
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
         
      - name: Add dev tag
        uses: shrink/actions-docker-registry-tag@v3
        with:
          registry: ghcr.io
          repository: ${{ github.repository }}/audit
          target: latest
          tags: |
            dev
            
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        runs-on: ubuntu-latest
        needs: [build]
        steps:
      - name: Image Build
          env:
          NAMESPACE: 85d4e0-tools
          BUILD_NAME: repomountie-master-build
          IMAGE_NAME: repomountie
          uses: redhat-developer/openshift-actions@v1.1
          with:
                  version: "latest"
                  openshift_server_url: ${{ secrets.OpenShiftServerURL}}
                  parameters: '{"apitoken": "${{ secrets.OpenShiftToken }}", "acceptUntrustedCerts": "true"}'
                  cmd: |
                    'version'
                    'start-build ${BUILD_NAME} -n ${NAMESPACE} --follow

