name: Pull Request
on:
  workflow_dispatch:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  builds:
    permissions:
      packages: write
    runs-on: ubuntu-22.04
    
    steps:
    - uses: actions/checkout@v3

    - name: Builds
      uses: bcgov-nr/action-conditional-container-builder@v1.1.1
      with:
        package: audit
        build_context: .
        build_file: docker/Dockerfile
        tag: latest 
        token: ${{ secrets.GITHUB_TOKEN }}
        triggers: ('docker/')
          
    - name: Docker login
      uses: docker/login-action@v2
      with:
        registry: ghcr.io 
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Add dev tag
      uses: shrink/actions-docker-registry-tag@v3
      with:
        registry: ghcr.io
        repository: ${{ github.repository }}/audit
        target: latest
        tags: |
          dev
    
    - name: Push images
      run: |
        docker pull ghcr.io/bcgov/von-bc-registries-audit/audit:dev
        docker tag ghcr.io/bcgov/von-bc-registries-audit/audit:dev image-registry.apps.silver.devops.gov.bc.ca/ca7f8f-tools/audit:dev
        docker login image-registry.apps.silver.devops.gov.bc.ca -u $(oc whoami) -p $(oc whoami -t)
        docker push image-registry.apps.silver.devops.gov.bc.ca/ca7f8f-tools/audit:dev



    # - name: Push To quay.io
    #   id: push-to-quay
    #   uses: redhat-actions/push-to-registry@v2
    #   with:
    #     image: ghcr.io/bcgov/von-bc-registries-audit/audit:latest
    #     tags: ghcr.io/bcgov/von-bc-registries-audit/audit:dev
    #     registry: image-registry.apps.silver.devops.gov.bc.ca
    #     username: rajpalc7@github
    #     password: sha256~ij7Bqqpk38tgGUiEPub-yg8JMbiBsoi3FnzurDx_ljI

    # - name: Log in to the Container registry
    #  uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
    #   with:
    #     registry: ghcr.io
    #     username: rajpalc7@github
    #     password: sha256~ij7Bqqpk38tgGUiEPub-yg8JMbiBsoi3FnzurDx_ljI

    # - name: Extract metadata (tags, labels) for Docker
    #   id: meta
    #   uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
    #   with:
    #     images: ghcr.io/bcgov/von-bc-registries-audit/audit:dev

    # - name: Build and push Docker image
    #   uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
    #   with:
    #     context: .
    #     push: true
    #     tags: latest


      
