# name: Pull Request
# on:
#   workflow_dispatch:
#   pull_request:

# concurrency:
#   group: ${{ github.workflow }}-${{ github.ref }}
#   cancel-in-progress: true

# jobs:
#   builds:
#     permissions:
#       packages: write
#     runs-on: ubuntu-22.04
    
#     steps:
#     - uses: actions/checkout@v3

#     - name: Builds
#       uses: bcgov-nr/action-conditional-container-builder@v1.1.1
#       with:
#         package: audit
#         build_context: .
#         build_file: docker/Dockerfile
#         tag: latest 
#         token: ${{ secrets.GITHUB_TOKEN }}
#         triggers: ('docker/')
          
#     - name: Docker login
#       uses: docker/login-action@v2
#       with:
#         registry: ghcr.io 
#         username: ${{ github.actor }}
#         password: ${{ secrets.GITHUB_TOKEN }}

#     - name: Add dev tag
#       uses: shrink/actions-docker-registry-tag@v3
#       with:
#         registry: ghcr.io
#         repository: ${{ github.repository }}/audit
#         target: latest
#         tags: |
#           dev
    
#     - name: Push images
#       run: |
#         docker pull ghcr.io/bcgov/von-bc-registries-audit/audit:dev
#         docker tag ghcr.io/bcgov/von-bc-registries-audit/audit:dev image-registry.apps.silver.devops.gov.bc.ca/ca7f8f-tools/audit:dev
#         docker login image-registry.apps.silver.devops.gov.bc.ca -u $(oc whoami) -p $(oc whoami -t)
#         docker push image-registry.apps.silver.devops.gov.bc.ca/ca7f8f-tools/audit:dev



name: Pull Request
on:
  workflow_dispatch:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  builds:
    permissions:
      packages: write
    runs-on: ubuntu-22.04
    outputs:
      image_digest: ${{steps.docker_build.outputs.digest}}

    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to the Container registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Force lowercase for Docker
      shell: bash
      id: lowercase
      run: |
        TAGS=$( echo "ghcr.io/${{ github.repository }}/audit:latest" | tr '[:upper:]' '[:lower:]' )
        echo "tags=${TAGS}" >> $GITHUB_OUTPUT

    - name: Build and push Docker image
      id: docker_build
      uses: docker/build-push-action@v3
      with:
        context: .
        file: docker/Dockerfile
        push: true
        tags: ${{ steps.lowercase.outputs.tags }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Show Image
      run: |
        echo 'imageid=${{steps.docker_build.outputs.imageid}}'
        echo 'digest=${{steps.docker_build.outputs.digest}}'

  deploy2dev:
    needs: builds
    permissions:
      packages: read
    runs-on: ubuntu-22.04
    environment: dev
    steps:    
    - name: Log in to the Container registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Setup Openshift CLI
      uses: redhat-actions/oc-login@v1
      with: 
        openshift_server_url: ${{vars.OPENSHIFT_SERVER_URL}}
        openshift_token: ${{secrets.OPENSHIFT_TOKEN}}
    - name: login in to Container Registry
      run: |
        oc login registry
    - name: tagging the image
      run: |
        docker pull ghcr.io/bcgov/von-bc-registries-audit/audit@${{needs.builds.output.image_digest}}
        docker tag ghcr.io/bcgov/von-bc-registries-audit/audit@${{needs.builds.output.image_digest}} image-registry.apps.silver.devops.gov.bc.ca/ca7f8f-tools/audit:dev  

    - name: Trigger Openshift
      run: |
       oc project ${{vars.NAMESPACE}} 
       oc login registry
       oc -n ${{vars.NAMESPACE}} rollout latest dc/audit; oc -n ${{vars.NAMESPACE}} rollout status dc/audit --watch
       

    # - name: Push To quay.io
    #   id: push-to-quay
    #   uses: redhat-actions/push-to-registry@v2
    #   with:
    #     image: ghcr.io/bcgov/von-bc-registries-audit/audit:latest
    #     tags: ghcr.io/bcgov/von-bc-registries-audit/audit:dev
    #     registry: image-registry.apps.silver.devops.gov.bc.ca
    #     username: rajpalc7@github
    #     password: sha256~ij7Bqqpk38tgGUiEPub-yg8JMbiBsoi3FnzurDx_ljI

    # - name: Log in to the Container registry
    #  uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
    #   with:
    #     registry: ghcr.io
    #     username: rajpalc7@github
    #     password: sha256~ij7Bqqpk38tgGUiEPub-yg8JMbiBsoi3FnzurDx_ljI

    # - name: Extract metadata (tags, labels) for Docker
    #   id: meta
    #   uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
    #   with:
    #     images: ghcr.io/bcgov/von-bc-registries-audit/audit:dev

    # - name: Build and push Docker image
    #   uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
    #   with:
    #     context: .
    #     push: true
    #     tags: latest


      
