name: Pull Request
on:
  workflow_dispatch:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  builds:
    permissions:
      packages: write
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Builds
        uses: bcgov-nr/action-conditional-container-builder@v1.1.1
        with:
          package: audit
          build_context: .
          build_file: docker/Dockerfile
          tag: latest 
          token: ${{ secrets.GITHUB_TOKEN }}
          triggers: ('docker/')
          
      - name: Docker login
        uses: docker/login-action@v2
        with:
          registry: ghcr.io 
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Add dev tag
        uses: shrink/actions-docker-registry-tag@v3
        with:
          registry: ghcr.io
          repository: ${{ github.repository }}/audit
          target: latest
          tags: |
            dev

       - name: "Docker tag and push image"
          run: |
            oc -n ca7f8f-dev rollout latest dc/audit; oc -n ca7f8f-dev rollout status dc/audit --watch
            docker pull ghcr.io/bcgov/von-bc-registries-audit/audit:dev
            docker tag ghcr.io/bcgov/von-bc-registries-audit/audit:dev image-registry.apps.silver.devops.gov.bc.ca/ca7f8f-tools/audit:dev
            docker login image-registry.apps.silver.devops.gov.bc.ca -u $(oc whoami) -p $(oc whoami -t)
            docker push image-registry.apps.silver.devops.gov.bc.ca/ca7f8f-tools/audit:dev
  # docker tag prime-webapi-backend ${{secrets.OPENSHIFT_IMAGE_REPOSITORY}}/${{secrets.OPENSHIFT_LICENSE_PLATE}}-tools/prime-webapi-backend:dev
  # docker push ${{secrets.OPENSHIFT_IMAGE_REPOSITORY}}/${{secrets.OPENSHIFT_LICENSE_PLATE}}-tools/prime-webapi-backend:dev