name: Pull Request
on:
  workflow_dispatch:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  builds:
    permissions:
      packages: write
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Builds
        uses: bcgov-nr/action-conditional-container-builder@v1.1.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          package: audit
          build_context: .
          build_file: docker/Dockerfile
          tag: latest

      - name: Docker login
        uses: docker/login-action@v2
        with:
          registry: ghcr.io 
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
         
      - name: Add dev tag
        uses: shrink/actions-docker-registry-tag@v3
        with:
          registry: ghcr.io
          repository: ${{ github.repository }}/audit
          target: latest
          tags: |
            dev
            

