name: Pull Request
on:
  workflow_dispatch:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  builds:
    permissions:
      packages: write
    runs-on: ubuntu-22.04
    
    steps:
    - uses: actions/checkout@v3

    - name: Builds
      uses: bcgov-nr/action-conditional-container-builder@v1.1.1
      with:
        package: audit
        build_context: .
        build_file: docker/Dockerfile
        tag: latest 
        token: ${{ secrets.GITHUB_TOKEN }}
        triggers: ('docker/')
          
    - name: Docker login
      uses: docker/login-action@v2
      with:
        registry: ghcr.io 
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Add dev tag
      uses: shrink/actions-docker-registry-tag@v3
      with:
        registry: ghcr.io
        repository: ${{ github.repository }}/audit
        target: latest
        tags: |
          dev

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: rajpalc7@github
        password: sha256~ij7Bqqpk38tgGUiEPub-yg8JMbiBsoi3FnzurDx_ljI
    
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        push: true
        tags: latest