name: Deploy
description: Deploy to OpenShift namespace

on:
  workflow_call:
    inputs:
      environment:
        description: the environment to deploy to
        required: true
      openshift_server_url: 
        description: openshift server url
        required: true
      image_digest:
        description: openshift image digest
        required: true
      namespace:
        description: namespace where we want to deploy the image
        required: true
      github_image_name:
        description:  github image name to be created
        required: true
      openshift_image_name:
        description: openshift image name to be created
        required: true 
    secrets:
      ROCKETCHAT_WEBHOOK:
        description: defining the rocket chat webhook url
        required: true
      ROCKETCHAT_TOKEN:
        description: defining the rocket chat token
        required: true
      # GITHUB_TOKEN:
        # description: secret token used to webhook github and rocketchat 
        # required: true
      OPENSHIFT_TOKEN:
        description: openshift server token
        required: true

jobs:
  publish:
    name: publish
    runs-on: ubuntu-latest
    steps:
      - name: Log in to the GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Openshift CLI
        uses: redhat-actions/oc-login@v1
        with:
          environment: ${{ inputs.environment }}
          openshift_server_url: ${{ inputs.openshift_server_url }}
          OPENSHIFT_TOKEN: ${{ secrets.OPENSHIFT_TOKEN }}

      - name: login in to OpenShift container registry
        shell: bash
        run: |
          oc registry login

      - name: Tag the image in the GHCR as ${{ inputs.environment }}
        shell: bash
        run: |
          docker pull ${{ inputs.github_image_name }}@${{ inputs.image_digest }}
          docker tag ${{ inputs.github_image_name }}@${{ inputs.image_digest }} ${{ inputs.github_image_name }}:${{ inputs.environment }}
          docker push ${{ inputs.github_image_name }}:${{ inputs.environment }}

      - name: Tag the image in the OpenShift container registry as ${{ inputs.environment }}
        shell: bash
        run: |
          docker pull ${{ inputs.github_image_name }}@${{ inputs.image_digest }}
          docker tag ${{ inputs.github_image_name }}@${{ inputs.image_digest }} ${{ inputs.openshift_image_name }}:${{ inputs.environment }}
          docker push ${{ inputs.openshift_image_name }}:${{ inputs.environment }}

      - name: Trigger Openshift
        shell: bash
        run: |
          echo starting rollout in ${{ inputs.namespace }}
          oc -n ${{ inputs.namespace }} rollout status dc/audit --watch

      - name: Rocket.Chat Notification
        uses: RocketChat/Rocket.Chat.GitHub.Action.Notification@master
        if: always()
        with:
          type:  ${{ job.status }}
          job_name: '*Deployment to ${{ inputs.environment }}*'
          mention: 'here'
          mention_if: 'failure'
          channel: '#test-gha'
          url: ${{ secrets.ROCKETCHAT_WEBHOOK }}
          commit: true
          token: ${{ secrets.ROCKETCHAT_TOKEN }}